### ISSUE TITLE
Adding a Repository License

### ISSUE THREAD

**Issue by SeanSanker** [alanjhughes/expo-shazamkit#3]
I'm interested in using and possibly contributing to this library. 
However, I've noticed that no license is specified.

Would you mind adding one (such as MIT, etc.)?

Thank you

**Comment by alanjhughes** [comment]
Hi, cool, I haven't worked on it in a while but I'll add the license this weekend. Feel free to contribute 👍

**Comment by SeanSanker** [comment]
Fantastic! Thank you so much!

**Comment by alanjhughes** [comment]
Done
