### ISSUE TITLE
Cannot get the example working

### ISSUE THREAD

**Issue by dailydm** [alanjhughes/expo-shazamkit#4]
Hello! 

First off, thank you so much for this library, I am super excited to give it a try. 

I am trying to copy the code in the example, and I am having some issues getting it to work. When I click the `Tap to Shazam` button, I do not get prompted to microphone permissions on my physical device and I instantly receive the below error: 

![IMG_3962](https://github.com/alanjhughes/expo-shazamkit/assets/16569232/b068f1a2-5f40-47cb-8c75-669f4007535c)

I have also confirmed that the bundle identifier in my `app.json` matches the identifier in my Apple Developer platform. 

I would imagine this is user error, but curious if you are able to reproduce

**Comment by dailydm** [comment]
Just updating this issue with some new info. After configuring the signing certificate appropriately in XCode, I am able to get the example working on a physical device, but not using Expo Go so I can go ahead and close the issue

**Comment by alanjhughes** [comment]
Hi @dailydm this project is incompatible with expo go. It is not an official part of the sdk. Apologies for the confusion
